# Created using wingetcreate 1.0.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.Okular
PackageVersion: 21.12.3
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://binary-factory.kde.org/job/Okular_Release_win64/lastSuccessfulBuild/artifact/okular-21.12.3-966-windows-msvc2019_64-cl.exe
  InstallerSha256: 5F1A80B36FDC664D34D8F37A67F6A8643AD8953DCA65ECC3CA1A40A4AE294574
ManifestType: installer
ManifestVersion: 1.1.0

